<a href="https://colab.research.google.com/github/GiulianoPepato/university-codes/blob/main/EP2-C%C3%A1lculo_Num%C3%A9rico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from scipy.linalg import lu
import pandas as pd

In [ ]:
def matrizes(n):
  print("Informe os coeficientes da matriz aumentada")
  matriz = []
  for i in range(n):
    linha = []
    for j in range(n+1):
      coef = float(input(f"Digite o valor de a_({i+1}{j+1}): "))
      linha.append(coef)
    matriz.append(linha)
  return np.array(matriz)

In [ ]:
n = int(input("Digite o número de equações do seu sistema: "))

Digite o número de equações do seu sistema: 3


In [ ]:
matriz = matrizes(n)

Informe os coeficientes da matriz aumentada
Digite o valor de a_(11): 0
Digite o valor de a_(12): 5.3
Digite o valor de a_(13): -1.9
Digite o valor de a_(14): 3.1
Digite o valor de a_(21): 11.9
Digite o valor de a_(22): 0
Digite o valor de a_(23): 1.9
Digite o valor de a_(24): 15.2
Digite o valor de a_(31): 1
Digite o valor de a_(32): -1
Digite o valor de a_(33): -1
Digite o valor de a_(34): 0


In [ ]:
matriz

array([[ 0. ,  5.2, -1.9,  3.1],
       [11.9,  0. ,  1.9, 15.2],
       [ 1. , -1. , -1. ,  0. ]])

#Questão b)

In [ ]:
def eliminacao_gaussn(M):
  i = 1
  for l in range(len(M)-1): #a l-ésima linha é a que vai multiplicada e somada/subtraída as demais
    for linha in range(len(M)-i):
      M[i:][linha] = M[i:][linha] - M[l] * (M[i:][linha][l]/M[l][l]) #M[i:] pega os elementos da matriz que estão logo abaixo da nossa l-ésima linha, no caso 'linha' é exatamente a linha que vai ser somada a esta.
      print(M)
    i += 1
  return M

In [ ]:
def solucaon(M):
  x_final = M[-1][-1]/M[-1][-2] #já resolve o sistema da última linha, pois é necessário para calcular as demais
  sol = [[x_final]] #lista das soluções
  linha = -1
  while len(sol) < len(M):
    ab = 0 #ab é soma de todos os termos a (coeficientes) com os b(soluções já encontradas)
    for coef in range(len(sol)):
      ab += M[linha-1][-coef-2] * sol[coef][0]
    x_n = (M[linha-1][-1] - ab)/M[linha-1][linha-2] # M[linha-1][-1] é o resultado da linha analisada e M[linha-1][linha-2] é o coeficiente
    sol.append([x_n])
    linha -= 1
  return sol[::-1]

In [ ]:
#Chat GPT programou
P, L, U = lu(matriz)
matriz_0 = P @ matriz #Gera a matriz pivotada

In [ ]:
matriz_0

array([[11.9,  0. ,  1.9, 15.2],
       [ 0. ,  5.3, -1.9,  3.1],
       [ 1. , -1. , -1. ,  0. ]])

In [ ]:
matriz_2 = eliminacao_gaussn(matriz_0)

[[11.9  0.   1.9 15.2]
 [ 0.   5.3 -1.9  3.1]
 [ 1.  -1.  -1.   0. ]]
[[11.9         0.          1.9        15.2       ]
 [ 0.          5.3        -1.9         3.1       ]
 [ 0.         -1.         -1.15966387 -1.27731092]]
[[11.9         0.          1.9        15.2       ]
 [ 0.          5.3        -1.9         3.1       ]
 [ 0.          0.         -1.51815443 -0.69240526]]


In [ ]:
solucao_G = solucaon(matriz_2)

In [ ]:
print('O vetor solução é composto por:')
n = 1
for solução in solucao_G:
  print(f'x_{n} = {solução[0]}')
  n+=1

O vetor solução é composto por:
x_1 = 1.2044908616187988
x_2 = 0.7484073107049608
x_3 = 0.456083550913838


#Questão c)

In [ ]:
def calculo_jacobi(matriz, solucao_i):
  x_k = []
  for k in range(len(matriz)):
    linha = np.delete(matriz[k], k)
    linha = np.delete(linha, -1)
    vetor_solucao_k = np.delete(solucao_i, k)
    solucao = ( matriz[k][-1] - np.dot(np.asarray(linha), np.asarray(vetor_solucao_k)) ) / matriz[k][k]
    x_k.append(solucao)
  return x_k

In [ ]:
def metodojacobi(matriz, chute, epsilon):
  solucao_i = chute
  solucoes = [solucao_i]
  erros = []
  k = 0
  K = []
  while abs( max(np.asarray(solucoes[-1]) - np.asarray(calculo_jacobi(matriz, solucao_i)) ) ) > epsilon:
    erros.append(abs( max(np.asarray(solucoes[-1]) - np.asarray(calculo_jacobi(matriz, solucao_i)) ) ))
    solucao_i = calculo_jacobi(matriz, solucao_i)
    solucoes.append(solucao_i)
    K.append(k)
    k += 1
  erros.append(abs( max(np.asarray(solucoes[-1]) - np.asarray(calculo_jacobi(matriz, solucao_i)) ) ))
  return solucoes, erros, k

In [ ]:
X = []
print("O vetor chute de solução é composto por: ")
for i in range(3):
  x = float(input(f'x_{i+1} = '))
  X.append(x)
X = np.array(X)

O vetor chute de solução é composto por: 
x_1 = 1
x_2 = 1
x_3 = 1


In [ ]:
Jmatriz = P @ matriz

In [ ]:
epsilon = 10**(-3)

In [ ]:
solucao_J, erros, k =  metodojacobi(Jmatriz, X, epsilon)

In [ ]:
#Gemini programou


# Pad the errors list with NaN if it has fewer elements than the number of
# iterations + 1 (The number of solutions is k+1, but the number of errors is k)


data = {
    'Iteração': range(len(solucao_J)),
    'Erro': erros,
    'Solução': solucao_J
}

df_jacobi = pd.DataFrame(data)

# Separate the 'Solução' column into individual columns
solucao_df = pd.DataFrame(df_jacobi['Solução'].tolist(), index=df_jacobi.index)

# Rename the new columns
solucao_df.columns = [f'I_{i+1}' for i in range(solucao_df.shape[1])]

# Concatenate the new columns with the original DataFrame (excluding the original 'Solução' column)
df_jacobi_expanded = pd.concat([df_jacobi.drop('Solução', axis=1), solucao_df], axis=1)

display(df_jacobi_expanded)

Iteração      Erro       I_1       I_2       I_3
0          0  1.000000  1.000000  1.000000  1.000000
1          1  0.358491  1.117647  0.943396 -0.000000
2          2  0.027822  1.277311  0.584906  0.174251
3          3  0.090289  1.249489  0.647373  0.692405
4          4  0.268484  1.166759  0.833126  0.602116
5          5  0.096249  1.181175  0.800759  0.333632
6          6  0.007470  1.224042  0.704510  0.380416
7          7  0.024241  1.216572  0.721281  0.519532
8          8  0.072084  1.194360  0.771153  0.495291
9          9  0.025841  1.198231  0.762463  0.423207
10        10  0.002005  1.209740  0.736622  0.435768
11        11  0.006508  1.207735  0.741124  0.473118
12        12  0.019353  1.201771  0.754514  0.466610
13        13  0.006938  1.202810  0.752181  0.447257
14        14  0.000538  1.205900  0.745243  0.450629

#Questão e)

In [ ]:
def calculo_GS(matriz, solucao_i):
  nova_solucao = solucao_i.copy()
  for k in range(len(matriz)):
    linha = np.delete(matriz[k], k)
    linha = np.delete(linha, -1)
    vetor_solucao_k = np.delete(nova_solucao, k)
    nova_solucao[k] = ( matriz[k][-1] - np.dot(np.asarray(linha), np.asarray(vetor_solucao_k)) ) / matriz[k][k] #atualiza o k-ésimo termo da lista de solução.
  return nova_solucao

In [ ]:
def metodoGS(matriz, chute):
  solucao_i = chute
  solucoes = [solucao_i]
  erros = []
  k = 0
  K = []
  while abs( max(np.asarray(solucoes[-1]) - np.asarray(calculo_GS(matriz, solucao_i)) ) ) > epsilon:
    erros.append(abs( max(np.asarray(solucoes[-1]) - np.asarray(calculo_GS(matriz, solucao_i)) ) ))
    solucao_i = calculo_GS(matriz, solucao_i)
    solucoes.append(solucao_i)
    K.append(k)
    k += 1
  erros.append(abs( max(np.asarray(solucoes[-1]) - np.asarray(calculo_GS(matriz, solucao_i)) ) ))
  return solucoes, erros, k

In [ ]:
X = []
print("O vetor chute de solução é composto por: ")
for i in range(3):
  x = float(input(f'x_{i+1} = '))
  X.append(x)
X = np.array(X)

O vetor chute de solução é composto por: 
x_1 = 1
x_2 = 1
x_3 = 1


In [ ]:
solucao_GS, erros, k = metodoGS(Jmatriz, X)

In [ ]:
#Gemini programou


data = {
    'Iteração': range(len(solucao_GS)),
    'Erro': erros,
    'Solução': solucao_GS
}

df_GS = pd.DataFrame(data)

# Use the solution data from the Gauss-Seidel method (solucao_GS)
solucao_df = pd.DataFrame(df_GS['Solução'].tolist(), index=df_GS.index)

# Rename the new columns
solucao_df.columns = [f'I_{i+1}' for i in range(solucao_df.shape[1])]

# Concatenate the new columns with the original DataFrame (excluding the original 'Solução' column)
df_GS_expanded = pd.concat([df_GS.drop('Solução', axis=1), solucao_df], axis=1)

display(df_GS_expanded)

Iteração      Erro       I_1       I_2       I_3
0          0  0.825749  1.000000  1.000000  1.000000
1          1  0.296023  1.117647  0.943396  0.174251
2          2  0.221700  1.249489  0.647373  0.602116
3          3  0.079478  1.181175  0.800759  0.380416
4          4  0.059523  1.216572  0.721281  0.495291
5          5  0.021338  1.198231  0.762463  0.435768
6          6  0.015981  1.207735  0.741124  0.466610
7          7  0.005729  1.202810  0.752181  0.450629
8          8  0.004291  1.205362  0.746452  0.458910
9          9  0.001538  1.204040  0.749420  0.454619
10        10  0.001152  1.204725  0.747882  0.456842
11        11  0.000413  1.204370  0.748679  0.455690